name: wings
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  # From dart.dev: Parses raw command-line arguments into a set of options and values.
  args: ^2.3.0

  # From dart.dev: internationalization and localization facilities
  intl: ^0.17.0

  # From dart.dev: A comprehensive, cross-platform path manipulation library for Dart.
  path: ^1.8.1

  # From theconduit.dev: A Dart library for manipulating pubspec files.
  pubspec: ^2.0.1

  # From dart.ninja: A Dart library for comparing and incrementing version numbers with Semantic Versioning.
  version:  ^2.0.0

  # From lukas-renggli.ch: library for parsing, traversing, querying, transforming and building XML documents.
  xml: ^5.3.1

  # From tools.dart.dev: A parser for YAML.
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0

  test: ^1.16.0
